name: 🔬
on:
   push:
      branches:
         - 'main'
jobs:
   test-node-os-coverage:
      name: Node ${{ matrix.node-version }} | ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
         matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            node-version: ['19']
      steps:
         - name: ➕ Actions - Checkout
           uses: actions/checkout@v3

         - name: ➕ Actions - Setup NodeJS
           uses: actions/setup-node@v3
           with:
              node-version: ${{ matrix.node-version }}

         - name: 🧪 Testing Service
           run: npm i --ignore-scripts && npm link "./" && npm run ci

   publish-npmjs:
      name: Publish Package to npmjs
      runs-on: ubuntu-latest
      needs: [test-node-os-coverage]
      if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'v')
      steps:
         - name: ➕ Actions - Checkout
           uses: actions/checkout@v3

         - name: ➕ Actions - Setup NodeJS
           uses: actions/setup-node@v3
           with:
              node-version: '19'
              check-latest: true
              registry-url: 'https://registry.npmjs.org'

         - name: 📥 Publishing Package
           run: npm publish
           env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
